version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: orangeDB
      MYSQL_USER: myuser  # Use a custom MySQL user instead of root
      MYSQL_PASSWORD: mypassword
    ports:
      - "8083:8083"
    restart: always
    networks:
      - my-network

    depends_on:
      - mysql
    volumes:
      - mysql-data:/var/lib/mysql

  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: rootpassword  # Secure root password
      MYSQL_DATABASE: orangeDB
      MYSQL_USER: myuser  # Create a new user
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  my-network:
