version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    networks:
      - app-network

  springboot-app:
    image: your_spring_boot_image:latest
    container_name: springboot_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my_database?autoReconnect=true&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_password
      SERVER_PORT: 8083
      SPRING_JACKSON_TIME_ZONE: Africa/Tunis
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE: Africa/Tunis
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SECURITY_JWT_SECRET_KEY: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      SECURITY_JWT_EXPIRATION_TIME: 3600000
      SPRING_SECURITY_ENABLED: true
      SPRING_MVC_ASYNC_REQUEST_TIMEOUT: 600000000000000
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
