version: '3.8'

services:
  app:
    image: sirine11/orange:latest
    container_name: spring-boot-app
    ports:
      - "8081:8080"  # Change 8081 to any available port on your host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/orange_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: orange_db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
